name: Deploy to Deno Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Build project
        run: deno cache deploy.ts

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "langfast2api" # Replace with your Deno Deploy project name
          entrypoint: "deploy.ts"